version: 'Build #{build}'
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
  - develop
  - /feature\/.*/
skip_tags: true
skip_branch_with_pr: true
image: Visual Studio 2019
configuration: Debug
platform: Any CPU
init:
- cmd: git config --global core.autocrlf true
max_jobs: 1
environment:
  CI_ARG_BuildOnly: 'false'
matrix:
  fast_finish: true
for:
  -
    branches:
      only:
        - develop
        - /feature\/.*/
    version: 'Build #{build} [{branch}]'
    deploy: off
build_script:
- ps: >-
    $Script:ErrorActionPreference = [System.Management.Automation.ActionPreference]::Stop;

    Microsoft.PowerShell.Core\Set-StrictMode -Version 1;


    & ./build.ps1 `
        -BuildOnly:([bool]::Parse($env:CI_ARG_BuildOnly))
test: off
after_build:
- ps: >-
    $Script:ErrorActionPreference = [System.Management.Automation.ActionPreference]::Stop;

    Microsoft.PowerShell.Core\Set-StrictMode -Version 1;

    function Print-Directory
    {
        Write-Host -ForegroundColor Magenta ('-' * 100)
    
        Get-ChildItem -Recurse `
            | Select-Object -Property FullName, Mode, Length `
            | Group-Object -Property { Split-Path -Parent $_.FullName } `
            | % { ''; ''; "Directory ""$($_.Name)"""; ''; $_.Group } `
            | Out-Host
    
        Write-Host -ForegroundColor Magenta ('-' * 100)
    }

    [string] $publishDirectory = '.publish'

    [string] $publishSubdirectory = 'inner'

    New-Item -ItemType Directory -Path $publishDirectory -Force | Out-Null

    New-Item -ItemType Directory -Path "$publishDirectory\$publishSubdirectory" -Force | Out-Null

    Print-Directory

    7z a """$publishDirectory\artifacts-$env:APPVEYOR_BUILD_NUMBER.zip""" -y -tzip -r -mx9 '-xr!".git"' "-xr!""$publishDirectory""" -- *.*

    7z a """$publishDirectory\scripts-$env:APPVEYOR_BUILD_NUMBER.zip""" -y -tzip -r -mx9 '-xr!".git"' "-xr!""$publishDirectory""" -- *.ps1

    #[string] $specialCharactersArchiveFilePath = "$publishDirectory\$publishSubdirectory\read me %100+ ($env:APPVEYOR_BUILD_NUMBER).zip"

    [string] $specialCharactersArchiveFilePath = "$publishDirectory\$publishSubdirectory\read me 100+ ($env:APPVEYOR_BUILD_NUMBER).zip"

    7z a """$specialCharactersArchiveFilePath""" -y -tzip -r -mx9 '-xr!".git"' "-xr!""$publishDirectory""" -- README.md

    Print-Directory
artifacts:
- path: '**/*.ps1'
  name: 'bin-$(APPVEYOR_BUILD_NUMBER)'
- path: '**/TestResult.txt'
  name: 'TestResult-$(APPVEYOR_BUILD_NUMBER)'
- path: '.publish\**\*.*'
  name: Artifacts
deploy:
- provider: GitHub
  on:
    branch: master
  release: 'v$(CI_DEPLOYMENT_VERSION)'
  description: '$(APPVEYOR_PROJECT_NAME) v$(CI_DEPLOYMENT_VERSION)'
  draft: true
  auth_token:
    secure: mSA6Z9mJtt2jbTlFZIWmAxTltAuZsOYbQkxQ/X2tOkpdp1SOJCjbR9dViEyOvAxD
  artifact: Artifacts
#notifications:
#- provider: Email
#  to:
#  - vitalii.maklai@gmail.com
#  - '{{commitAuthorEmail}}'
#  subject: '[AppVeyor] {{projectName}} {{buildVersion}}: Build {{status}} ({{branch}} @ {{commitId}})'
#  on_build_success: true
#  on_build_failure: true
#  on_build_status_changed: false
