version: 0.0.{build}
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
skip_tags: true
image: Visual Studio 2019
configuration: Debug
platform: Any CPU
init:
- cmd: git config --global core.autocrlf true
environment:
  matrix:
  - CI_ARG_BuildOnly: 'true'
  - CI_ARG_BuildOnly: 'false'
    CI_ARG_TestRuntime: 'net40'
  - CI_ARG_BuildOnly: 'false'
    CI_ARG_TestRuntime: 'net472'
build_script:
- ps: >-
    $Script:ErrorActionPreference = [System.Management.Automation.ActionPreference]::Stop


    & ./build.ps1 -BuildOnly:$([bool]::Parse($env:CI_ARG_BuildOnly)) -TestRuntime:$env:CI_ARG_TestRuntime
artifacts:
- path: '**/*'
  name: AllFiles
deploy: off
notifications:
- provider: Email
  to:
  - vitalii.maklai@gmail.com
  - '{{commitAuthorEmail}}'
  subject: '[AppVeyor] {{projectName}} {{buildVersion}}: Build {{status}} ({{branch}} @ {{commitId}})'
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: false