version: '1.0.{build}'
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
  - develop
  - /feature\/.*/
skip_tags: true
skip_branch_with_pr: true
image: Visual Studio 2019
configuration: Debug
platform: Any CPU
init:
- cmd: git config --global core.autocrlf true
environment:
  global:
    CI_ARG_BuildOnly: 'false'
    CI_ARG_Deploy: 'false'
    CI_ARG_TestFramework: ''
  matrix:
  - job_group: TestJobs
    job_name: 'Test: net40'
    CI_ARG_TestFramework: 'net40'
  - job_group: TestJobs
    job_name: 'Test: net472'
    CI_ARG_TestFramework: 'net472'
  - job_group: DeployJobs
    job_name: Deploy
    job_depends_on: TestJobs
    CI_ARG_BuildOnly: 'true'
    CI_ARG_Deploy: 'true'
matrix:
  fast_finish: true
for:
  -
    branches:
      only:
        - develop
        - /feature\/.*/
    version: '[{branch}] #{build}'
    environment:
      CI_ARG_Deploy: 'false'
    deploy: off
  -
    matrix:
      only:
        - job_group: TestJobs
    artifacts:
      - path: '**/TestResult.txt'
        name: 'TestResult-$(APPVEYOR_BUILD_VERSION)'
  -
    matrix:
      only:
        - branch: master
        - job_group: DeployJobs
    after_build:
    - ps: >-
        $Script:ErrorActionPreference = [System.Management.Automation.ActionPreference]::Stop;

        [string] $publishDirectory = '.publish'

        New-Item -ItemType Directory $publishDirectory -Force | Out-Null

        Write-Host -ForegroundColor Magenta ('-' * 100)

        Get-ChildItem -Recurse `
           | Select-Object -Property FullName, Mode, Length `
           | Group-Object -Property { Split-Path -Parent $_.FullName } `
           | % { ''; ''; "Directory ""$($_.Name)"""; ''; $_.Group } `
           | Out-Host

        Write-Host -ForegroundColor Magenta ('-' * 100)

        7z a """$publishDirectory\artifacts-$env:APPVEYOR_BUILD_VERSION.zip""" -y -tzip -r -mx9 '-xr!".git"' "-xr!""$publishDirectory""" -- *.*

        7z a """$publishDirectory\scripts-$env:APPVEYOR_BUILD_VERSION.zip""" -y -tzip -r -mx9 '-xr!".git"' "-xr!""$publishDirectory""" -- *.ps1
    artifacts:
      - path: '.publish\*.*'
        name: Artifacts
build_script:
- ps: >-
    $Script:ErrorActionPreference = [System.Management.Automation.ActionPreference]::Stop;


    Write-Host -ForegroundColor Magenta ('-' * 100)

    Get-ChildItem env:* | Sort-Object Name | Select-Object Name, Value | Format-Table * -Wrap

    Write-Host -ForegroundColor Magenta ('-' * 100)

    Get-ChildItem -Recurse `
       | Select-Object -Property FullName, Mode, Length `
       | Group-Object -Property { Split-Path -Parent $_.FullName } `
       | % { ''; ''; "Directory ""$($_.Name)"""; ''; $_.Group } `
       | Out-Host

    Write-Host -ForegroundColor Magenta ('-' * 100)


    & ./build.ps1 `
        -BuildOnly:([bool]::Parse($env:CI_ARG_BuildOnly)) `
        -Deployment:([bool]::Parse($env:CI_ARG_Deploy)) `
        -TestFramework:$env:CI_ARG_TestFramework
deploy:
- provider: GitHub
  on:
    branch: master
    CI_ARG_Deploy: true
  release: 'v$(APPVEYOR_BUILD_VERSION)'
  description: '$(APPVEYOR_PROJECT_NAME) v$(APPVEYOR_BUILD_VERSION)'
  draft: true
  auth_token:
    secure: mSA6Z9mJtt2jbTlFZIWmAxTltAuZsOYbQkxQ/X2tOkpdp1SOJCjbR9dViEyOvAxD
  artifact: Artifacts
#notifications:
#- provider: Email
#  to:
#  - vitalii.maklai@gmail.com
#  - '{{commitAuthorEmail}}'
#  subject: '[AppVeyor] {{projectName}} {{buildVersion}}: Build {{status}} ({{branch}} @ {{commitId}})'
#  on_build_success: true
#  on_build_failure: true
#  on_build_status_changed: false
