version: 0.0.{build}
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
skip_tags: true
image: Visual Studio 2019
configuration: Debug
platform: Any CPU
init:
- cmd: git config --global core.autocrlf true
environment:
  matrix:
  - TestRuntime: net40
  - TestRuntime: net472
build_script:
- ps: "& './build.ps1' -TestRuntime $env:TestRuntime"
artifacts:
- path: '**/*'
  name: AllFiles
deploy: off
notifications:
- provider: Email
  to:
  - vitalii.maklai@gmail.com
  - '{{commitAuthorEmail}}'
  subject: '[AppVeyor] {{projectName}} {{buildVersion}}: Build {{status}} ({{branch}} @ {{commitId}})'
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: false